export const SECTION_LABELS = {
  site: "Site Settings (Nav, Contact, Social, Footer)",
  gallery: "Homepage Gallery Strip",
  home: "Home Page",
  about: "About Page",
  services: "Services (List + Details)",
  projects: "Projects (List + Details)",
  areas: "Areas We Serve (List + Details)",
  team: "Meet The Builders",
  testimonials: "Testimonials",
  article: "Article",
  contact: "Contact Page",
  contractor: "Subcontractor Application Page",
  "ask-to-expert": "Ask To Expert Page",
  estimator: "Project Estimator (Pricing & Copy)",
  privacy: "Privacy Policy",
  terms: "Terms & Conditions",
  "thank-you": "Thank You Page",
  "not-found": "404 Not Found Page",
};

export const SECTION_GROUPS = {
  site: "Global",
  gallery: "Global",
  home: "Pages",
  about: "Pages",
  contact: "Pages",
  contractor: "Pages",
  "ask-to-expert": "Pages",
  "thank-you": "Pages",
  "not-found": "Pages",
  privacy: "Legal",
  terms: "Legal",
  services: "Collections",
  projects: "Collections",
  areas: "Collections",
  team: "Collections",
  testimonials: "Collections",
  article: "Collections",
  estimator: "Tools",
};
